Webify - Final Project Web Dev Bootcamp 2024
Technigo/project-final pull request #48
Opened 2024-06-18 06:26 UTC by SofieFerrari

Frontend: https://webify-templates.netlify.app/

Backend: [https://webify-peace.onrender.com ](https://webify-peace.onrender.com%E2%80%A8/)

Mai Kanetaka: 
[maikanetaka]
https://www.linkedin.com/in/maikanetaka 
https://maikanetaka.netlify.app/

Wen Zhao: 
[wwenzz]
https://www.linkedin.com/in/wendywenzhao
https://wen-portfolio.netlify.app/

Sofie Ferrari Strahl: 
[SofieFerrari]
https://www.linkedin.com/in/sofie-ferrari-strahl-495486214
https://sofieferraristrahl.netlify.app/

2024-06-19 13:04 UTC, AntonellaMorittu requested changes
Hello Mai, Sofie and Wen and grattis! 🎓 

I am so impressed with the app you delivered, beginning from the clean design to the smooth flow you proved to be capable of developing and shipping web apps! I can see your planning was meticulous, from the wireframe to the design on Figma. You nailed aspects like responsiveness and positive user experience, the product is finalised and refined in many aspects, including animations, info states, a breadcrumb component, besides  features like products gather by tags and authentication that take the app to a really high level.

The code structure is clean and the backend is robust, really good you divided your code in modules on the server-side 💯 

Now that said, I spotted some few things that can be improved and little bugs to be squashed:

- **accessibility**: should score at least 95 on Lighthouse (basic requirement)
- upload SVG images rather than any other format to preserve high definition
- if logged out, remove items from cart doesn’t work (clear cart does!)
- delete all _console.log()_ added during development on the frontend
- UX: when selecting an option from footer, render the page by scrolling to the top, or the user won’t notice the selection has been applied
- when selecting a category from the footer, the url is uploaded but not the content of the page

Again congratulations for shipping a final product in only 3 weeks! Thank you for reviewing and submitting the changes requested.

2024-06-19 13:04 UTC, NellaMori commented on frontend/src/pages/Checkout.jsx
> +    console.log(data);
please remove the console.log() used during development 🧹

2024-06-20 12:33 UTC, wwenzz commented
Hi Antonella @AntonellaMorittu thank you for your constructive feedback! We really appreciate that 😄 

However, there are two comments that we have already adjusted/implemented.

- **"if logged out, remove items from cart doesn’t work (clear cart does!)"**: This we have fixed yesterday and now logout clears the cart too!
- **"when selecting a category from the footer, the url is uploaded but not the content of the page"**: The category from footer modifies the query params in the URL AND also applies the category filter now.

Could you please double check if you still see these as issues? As we tested out and it worked as expected.

Lastly, we find it a bit confusing in terms of this comment **"upload SVG images rather than any other format to preserve high definition"**, do all images have to be in SVG format? What about larger pictures? Can we keep those larger pictures in png/jpg/webp format? We have made icons into svgs, but just not sure if considering performance and resolution does it have to be in SVG?

/Mai, Sofie & Wen

2024-06-21 21:21 UTC, wwenzz commented
Hej @AntonellaMorittu we have adjusted our code based on your suggestions.

**- accessibility: should score at least 95 on Lighthouse (basic requirement)**
Now we have improved our accessibility score to 100.
<img width="1477" alt="Screenshot 2024-06-21 at 23 16 14" src="https://github.com/Technigo/project-final/assets/117687564/3621e2a6-d39d-4a54-9f71-8b43801999d0">

**- upload SVG images rather than any other format to preserve high definition**
We have cleaned up our images and converted the icons and smaller images to SVG. Yet we think larger images would be better in png/jpg format.

**- if logged out, remove items from cart doesn’t work (clear cart does!)**
This has been fixed and now logout clears the cart.

**- delete all console.log() added during development on the frontend**
All console logs have been removed in frontend folder.

**- UX: when selecting an option from footer, render the page by scrolling to the top, or the user won’t notice the selection has been applied**
We have implemented the scroll-to-top function that would work on the links in the footer

**- when selecting a category from the footer, the url is uploaded but not the content of the page**
We have fixed this issue and now the category from footer will execute filter function as well as modify the query params.

I hope what we have done meet your expectations and if anything missing please let us know.

Again, thank you so much for your detailed feedback and these help us improve our project a lot!

/Mai, Sofie and Wen

2024-06-24 11:37 UTC, AntonellaMorittu approved these changes

2025-02-18 05:59 UTC, closed without merging