eGo
Technigo/project-final pull request #53
Opened 2024-06-20 11:25 UTC by vittoriamatteoli

##Netlify link 
https://ego-app.netlify.app/

##Render link
https://project-final-1-4w43.onrender.com/

##Collaborators
[El1an3, Yifan-858,kathinka,vittoriamatteoli]

2024-06-24 12:04 UTC, AntonellaMorittu requested changes
Hello Eliane, Kathinka, Vittoria and Yifan, big congratulations on arriving to the end of the bootcamp and deliver your own app! 🎓 
The app works well, has a good flow and is properly planned and organised, both on the frontend and the backend. The code is really well structured and written, clean formatted and readable, the backend is robust and structured in modules to improve scalability and readability. I'm impressed you had your own design, wireframe and made your own logos, such a professional way to work! Nice work with animations, the app is also accessible and fully-responsive! You should be PROUD! ⭐ 

Now, here's some fixes to apply to make it work flawlessly:
- after selecting a trip, the top right section with the chart is not updated unless performing a page refresh
- as soon as you click on eGo logo, it logs out- user should be persistently logged in unless it logs out

And here's some aspects that can be taken into consideration for further improvement:
- would be nice an onboarding / info on how to use the app or about points in the app (some simple descriptions would be enough)

I'll ask you to apply the fixes mentioned, thank you and again big congratulations 👏 You made it 🚀

2024-06-24 12:04 UTC, NellaMori commented on .vscode/settings.json
please add this to .gitignore and delete the folder 🧹

2024-06-24 12:04 UTC, NellaMori commented on frontend/src/Globalstyles.jsx
don't forget to format your files 👍

2024-06-25 13:44 UTC, AntonellaMorittu approved these changes

2025-02-18 05:59 UTC, closed without merging