ArtCanvas
Technigo/project-final pull request #54
Opened 2024-06-20 13:14 UTC by Josephineoderland

https://art.dev.josephine.nu/
https://art.dev.josephine.nu/api/

2024-06-24 13:06 UTC, AntonellaMorittu requested changes
Hi Josephine, and big congratulations for completing the bootcamp and delivering your final project! 🎓 
Praise for working alone and shipping an app in only 3 weeks, you should be proud! ⭐ 

The app is working even if not perfectly, and you were ambitious in shipping many different functionalities that will require more testing and refinement. Either ways, the code is really well structured and written, clean formatted and readable, the backend is robust and structured in modules to improve scalability and readability.
I think it's very cool you implemented a chat but I couldn’t test it as I have no friends.
You nailed responsiveness and accessibility. 
Now here's some tips and things to consider to improve the app flow and UX:

- avoid usage of the app if logged out - as half of it won’t work and the user is lost
- please add a README for your app
- please add app usage info. Overall the app is in need of UI info text and explanation on how to use the app.
- avoid UI flickering of elements / re-render of the whole page (i.e. when you click "generate random characters")
- search user to befriend, based on what criteria? Some info text would help the user understanding how to use the app in the best way
- Please remove the `console.log()`s from the frontend used during developement
nough)

Generally it would have been better to focus on a simple MVP and simple functionalities well tested, rather than have extensive features and structure but weaker.

I'll ask you to apply the fixes mentioned, thank you and again big congratulations 👏 You made it 👩‍🎤

2024-06-24 13:06 UTC, NellaMori commented on frontend/src/AppRoutes.jsx
> +      <Route path="/PlaceAndFeelG" element={<PlaceAndFeelG />} />
be consistent with the naming convention, in url there should only be kebab-case and not PascalCase names 👍

2024-07-08 18:25 UTC, Josephineoderland commented
Hi, 

I pushed up the changes as requested.
But I don't understand what you mean with the flickering? I have asked colleagues and they don't understand either. Please explain further what you ment or if the changes I have done is enough.

2024-08-05 10:05 UTC, HIPPIEKICK approved these changes
I agree with Antonella that there's still room for UI improvements, as it might not be completely intuitive, but I think you've improved it and it reaches the requirements, so I'll approve now.

I'm not a 100% sure, but I think the flickering refers to this 👀 
https://github.com/user-attachments/assets/bccf3610-da69-43d6-a114-2e6e76265581

2024-08-05 18:29 UTC, Josephineoderland commented
Hey! Thanks for explaining about the flickering! Where do I get the certificate? 😊Skickat från min iPhone5 aug. 2024 kl. 12:05 skrev Matilda Brunemalm ***@***.***>:﻿
@HIPPIEKICK approved this pull request.

I agree with Antonella that there's still room for UI improvements, as it might not be completely intuitive, but I think you've improved it and it reaches the requirements, so I'll approve now.
I'm not a 100% sure, but I think the flickering refers to this 👀
https://github.com/user-attachments/assets/bccf3610-da69-43d6-a114-2e6e76265581

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-02-18 05:59 UTC, closed without merging