glim. Final project by Izabel, Linda and Martin
Technigo/project-final pull request #56
Opened 2024-06-21 09:23 UTC by Martin-Joensson

Netlify link
https://glim-skincare.netlify.app/

Collaborators
[izzibizz, linda-f, martin-joensson]

2024-06-24 15:00 UTC, HIPPIEKICK requested changes
Hi Izabel, Linda & Martin! Big congrats to completing your final project 🚀 🌕 🦩 
I think we were all impressed by your project during the graduation demo but I want to say it again, that it looks so professional in so many ways. The design is on point, 
I love the frosted header, the color scheme and image choices. And small little nice things, like the loading sparkles ✨ You also nailed the functionality of this app, and I'm impressed that you successfully implemented Stripe (thanks for sharing demo card details 😉). Your app is responsive and the UX is thought through. The code is mostly clean, but I left some comments on where I think you can benefit from refactoring.

Some other things that I think you can work on for further improvements and to make your app work even better:
- After signing up it would be nice to stay logged in
- Featured products carousel started in the end for me, so clicking right doesn’t do anything
- Check spelling of your copy (will make it look more professional)
- On the About page, it would be nice if the LinkedIn and GitHub were icons like in the footer, or at least that they stand out as link and don’t just look like regular body text
- A favicon would be nice!
- Personal design thoughts:
  - On the /products page, I think it would be nice if you visually showed that the dropdowns are dropdowns. They kind of look like buttons now I think?
  - Font on the buttons for products doesn’t have the same font?
- Please please please make links open in a new tab
- Would be nice if the sorting and filtering was saved if I click a product and then go back
- Would be nice to be able to edit my user profile (I saw the WIP 👍)

**Needs fixing 👇**
**- Accessibility: should score at least 95 on Lighthouse**
**- I should not be able to create a new user if the user already exists** 
**- Potential bug:**
    - I signed up with matilda@technigo.io
    - I signed up again with matilda@technigo.io (no error)
    - I deleted my profile (should maybe add a ”Are you sure?” popup hehe.)
    - I signed up again with matilda@technigo.io (successfully)
    - But… I can’t log in. I get ”The email or password is incorrect, please try again”
    - Is it because I didn’t fill in all required fields in the registration? Then you need to make it required in the frontend as well

I left some comments around your code as well, so have a look when you have time, but please fix the bold parts in the list above ☝️

Really great job and effort overall, you should be proud! 💪

2024-06-24 15:00 UTC, HIPPIEKICK commented on backend/models/productSchema.js
👍

2024-06-24 15:00 UTC, HIPPIEKICK commented on backend/models/reviewSchema.js
This will be nice ✨

2024-06-24 15:00 UTC, HIPPIEKICK commented on backend/routes/stripe.js
Very nice!

2024-06-24 15:00 UTC, HIPPIEKICK commented on backend/routes/users.js
> +    }
You have a lot of validation here, which is really good, but what about if a user already exists with that specific email adress?

And would it be possible to make this more DRY somehow? 👀

2024-06-24 15:00 UTC, HIPPIEKICK commented on backend/routes/users.js
> +    });
Would be nice if a successful registration resulted in automatic login 😄

2024-06-24 15:00 UTC, HIPPIEKICK commented on backend/routes/users.js
> +});
Nice, I was hoping you'd work on something like this 👍

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/index.html
> +    <link rel="icon" type="image/svg+xml" href="/glim-logo.svg" />
This doesn't show for me 😢

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/package.json
> +    "tailwindcss": "^3.4.3",
Would be nice if you'd add a little description of what you're using all these dependencies for. I know we haven't talked much about documentation, but I think it can be nice

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/App.jsx
>    );
Why do you mount your Footer in many places and not on top level? 👀 #DRY

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/components/CheckoutForm.jsx
> +  };
This could be broken out to a utils file

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/components/CheckoutForm.jsx
> +  };
And this could be broken out perhaps

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/components/Navigation.jsx
> +  };
Nice little feature!

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/components/Navigation.jsx
This file is quite big, would it be possible to refactor into smaller components?

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/components/OrderHistory.jsx
What does this mean? I don't think I saw it

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/components/ReviewCard.jsx
> +//THis ReviewCard is not implemented yet. It is here for future use.
Looking forward!

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/pages/ShoppingCart.jsx
> +        {orderHistory.length > 0 && <OrderHistory />}
Aha, so OrderHistory is just all the products in the cart right now? 👀

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/pages/ShoppingCart.jsx
> +  };
These could be broken out into utils files

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/src/store/useProductsStore.jsx
> +          });
Nicely implemented 💰

2024-06-24 15:00 UTC, HIPPIEKICK commented on frontend/tailwind.config.js
Well customized 👍

2024-06-26 07:18 UTC, linda-f commented
Hi @HIPPIEKICK 
We looked at the needs fixing points and fixed them.
Thank you for checking again. 
We also tested accessibility on all pages and got at least 95 everywhere. See attached screenshots.
We also fixed the link for the favicon for the browser, you should be able to see it now ;)
![desktop-about](https://github.com/Technigo/project-final/assets/154750388/7da760ce-5162-4a99-aaa9-5ef21792d983)
![desktop-cart](https://github.com/Technigo/project-final/assets/154750388/9e3af058-7ee4-422c-b43d-92d2a1e6967a)
![desktop-home](https://github.com/Technigo/project-final/assets/154750388/379d42e6-89d2-4eb6-b099-7b27f2b02c31)
![desktop-products](https://github.com/Technigo/project-final/assets/154750388/09969d06-8e74-40ae-bbca-1f54fe187fce)
![desktop-signup](https://github.com/Technigo/project-final/assets/154750388/f1796097-fce9-4e6f-96f7-b9d2a470de5d)
![mobile-about](https://github.com/Technigo/project-final/assets/154750388/2b18adfc-8c63-43bc-9f83-e49a40c513c4)
![mobile-cart](https://github.com/Technigo/project-final/assets/154750388/ea3b70e5-b7c8-43bd-b7f2-e614f155494a)
![mobile-home](https://github.com/Technigo/project-final/assets/154750388/79aba9d6-7b7f-41da-9542-d17976983036)
![mobile-products](https://github.com/Technigo/project-final/assets/154750388/2a2ad93b-a8f7-4928-8046-21bc1eabe057)
![mobile-signup](https://github.com/Technigo/project-final/assets/154750388/c15b1d77-e220-435f-80bf-55fc2ff45639)
![desktop-profile](https://github.com/Technigo/project-final/assets/154750388/4922d2f3-3e0d-4ae5-81eb-5897e21994e8)
![desktop-singlep](https://github.com/Technigo/project-final/assets/154750388/8185e22b-0870-4e0b-af3f-1dd62329bdfb)
![mobile-profile](https://github.com/Technigo/project-final/assets/154750388/69d4b7ac-4298-4344-bbb0-5e404bd419f0)
![mobile-singlep](https://github.com/Technigo/project-final/assets/154750388/98d16d69-15a8-4d1a-85e3-5ef5c6e4ca72)

2024-06-26 07:23 UTC, AntonellaMorittu approved these changes

2024-06-27 07:45 UTC, HIPPIEKICK approved these changes

2025-02-18 05:59 UTC, closed without merging