project-final
Technigo/project-final pull request #57
Opened 2024-06-21 13:21 UTC by Paulajungaker

Netlify: https://palma-rentals.netlify.app/

2024-06-25 08:34 UTC, AntonellaMorittu requested changes
Hi Paula, big congratulations on arriving to the end of the bootcamp and deliver your own app! 🎓 

The app MVP is working pretty well even if there are some little things that need to be adjusted and tested, you were ambitious in shipping an app entirely built alone in only 3 weeks, so kudos to that! 👏 The code is really well structured and written, formatted and readable (good use of comments). the backend is robust and structured in modules to improve scalability and readability. You nailed responsiveness and accessibility. 

Now here's some tips and things to consider to improve the app flow. 

UX/UI fixes:
- make the flow clearer: items for rent are not visible if not logged-in, write info text to guide the user
- if user is logged in, hide all log in/create account buttons 
- cart should be on the top navbar rather than at the bottom of the page
- once you click on cart, the user should be taken to the top of the page (now it’s at the bottom)
- very big margin and spaces in the layout, makes the content of the page grow and involves a lot of scrolling
- keep an eye on spelling mistakes (address not address, shopping cart not shopping cart)
- after an order is placed, as a user I would like to see my orders listed
- use only svg format for images
- form to ask for info doesn’t work in the frontend - get a page not found. Did you deploy your routes?
- there’s no `about` section or social media links, could be good for you to promote your work 

Code tips:
- remove assets if unused
- axios instead of built in Fetch API - any particular reason? Try to avoid installing external libraries if possible
- Folder structure: in React the convention is to have the .`css` file together in the same folder with the `Component.jsx `file

I'll ask you to apply the fixes mentioned, thank you and again, congratulation! 🥇

2024-06-28 07:30 UTC, AntonellaMorittu commented
Hi Paula, I saw you applied some changes, great! I couldn't test your app though, as soon as I try to login the request gets stuck in a pending state. Can you please double-check your deployed auth api? Thank you :)

2024-08-05 09:36 UTC, HIPPIEKICK requested changes
Hi Paula!
I wanted to write a little update. Apart from what Antonella wrote, I'd like to ask you to create a loading indicator as render is so slow. When I logged in for the first time, I just saw text linking me to the cart but no rentals (due to slow loading). Also, images are broken 👀 And I find it a bit confusing that when clicking Cart, I only see the Profile text and the option to Log out at first. Can't the logout be its own button in the nav instead of at the top of the cart?

Here's what's left of Antonella's list:

UX/UI fixes:
- [x] make the flow clearer: items for rent are not visible if not logged-in, write info text to guide the user
- [x] if user is logged in, hide all log in/create account buttons
- [x] cart should be on the top navbar rather than at the bottom of the page
- [x] once you click on cart, the user should be taken to the top of the page (now it’s at the bottom)
- [x] very big margin and spaces in the layout, makes the content of the page grow and involves a lot of scrolling
- [x] keep an eye on spelling mistakes (address not address, shopping cart not shopping cart)
- [ ] after an order is placed, as a user I would like to see my orders listed
- [x] use only svg format for images
- [ ] form to ask for info doesn’t work in the frontend - get a page not found. Did you deploy your routes?
- [x] there’s no about section or social media links, could be good for you to promote your work 

Code tips:
- [ ] remove assets if unused
- [x] axios instead of built in Fetch API - any particular reason? Try to avoid installing external libraries if possible
- [ ] Folder structure: in React the convention is to have the .css file together in the same folder with the Component.jsx file

PS.
Another thing I found, this form could use a little CSS love:
![Skärmavbild 2024-08-05 kl  11 33 18](https://github.com/user-attachments/assets/ac720aa8-2ecc-4629-8fed-6436df2eddd4)

2024-09-19 07:54 UTC, HIPPIEKICK commented
OK, made this new list of what's left for clarity:
[] indicate that the page is loading somehow, whenever you make a request to Render
[] fix broken images
[] after an order is placed, as a user I would like to see my orders listed (I see a start of this, but it says "Rental name not available")
[] form to ask for info doesn’t work in the frontend - get a page not found. Did you deploy your routes?

And potentially also this:
I find it a bit confusing that when clicking Cart, I only see the Profile text and the option to Log out at first. Can't the logout be its own button in the nav instead of at the top of the cart?

2025-02-18 05:59 UTC, closed without merging