Final project-ParkHive
Technigo/project-final pull request #59
Opened 2024-06-23 14:00 UTC by trista1987

## Netlify link
Frontend: https://parkhive.netlify.app/
Backend: https://parkhive.onrender.com

## Collaborators
[Citronskal, trista1987]

2024-06-25 13:33 UTC, AntonellaMorittu requested changes
Dear Yia and Trista, stort grattis! 🎓 

Congrats for completing the bootcamp and shipping a fantastic final project! I'm really impressed with your result, the app looks very professional and ready to be used by real users, well done!

I like how you developed an app with a smooth flow, clear UI and good UX, I love the animations for loading state and small details like the button to scroll to top, very nice touch! You worked well also when writing your code, nicely formatted and structured, both in the backend and the frontend. 
In this final project, we asked you to plan your bigger project work, further deepen your knowledge in web development and finally explore new technologies and you definitely succeeded in all these aspects! 
You nailed responsiveness as well, shipping such result in only 3 weeks this is truly admirable. You should be PROUD!
Now, here's some adjustments to take into consideration to improve the quality of your app. 

**Fixes to meet the basic requirements:**
- Accessibility: should score at least 95 on Lighthouse
- deploy routes on Netlify

Tips to improve your app:
- links open to a new tab
- social media links don’t have a link - better to hide part of the app in production unless they have a functionality
- make the map for the park bigger to fit in some empty space in desktop screens

Please fix the accessibility access and deploy your routes. Once again my congratulations for your hard work, you're ready to be graduated developers now ⭐

2024-06-25 17:42 UTC, trista1987 commented
> Dear Yia and Trista, stort grattis! 🎓
> 
> Congrats for completing the bootcamp and shipping a fantastic final project! I'm really impressed with your result, the app looks very professional and ready to be used by real users, well done!
> 
> I like how you developed an app with a smooth flow, clear UI and good UX, I love the animations for loading state and small details like the button to scroll to top, very nice touch! You worked well also when writing your code, nicely formatted and structured, both in the backend and the frontend. In this final project, we asked you to plan your bigger project work, further deepen your knowledge in web development and finally explore new technologies and you definitely succeeded in all these aspects! You nailed responsiveness as well, shipping such result in only 3 weeks this is truly admirable. You should be PROUD! Now, here's some adjustments to take into consideration to improve the quality of your app.
> 
> **Fixes to meet the basic requirements:**
> 
> * Accessibility: should score at least 95 on Lighthouse
> * deploy routes on Netlify
> 
> Tips to improve your app:
> 
> * links open to a new tab
> * social media links don’t have a link - better to hide part of the app in production unless they have a functionality
> * make the map for the park bigger to fit in some empty space in desktop screens
> 
> Please fix the accessibility aspect and deploy your routes. Once again my congratulations for your hard work, you're ready to be graduated developers now ⭐

Hi Antonella! 
Thanks for your suggetsions! 😁 
I have added the deploy routes on Netilfy and Yia has changed accessibility. But we have got different accessibility score from our computers, the score is 96 from Yia's computer and the score is 95 from my computer. So we are not sure whether using different servers and locations will affect the score?

2024-06-25 19:11 UTC, Citronskal commented
Hi Antonella, like Trista mentioned, we have made some small adjustments and accessibility is above 95 on both our devices. 
<img width="1440" alt="Screenshot 2024-06-25 at 7 56 48 PM" src="https://github.com/Technigo/project-final/assets/108352267/4c6230fc-73dd-428b-8490-e9b20dc96bd4">

2024-06-26 12:03 UTC, AntonellaMorittu approved these changes

2025-02-18 05:59 UTC, closed without merging